# Generated by Django 4.2.1 on 2023-06-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
    ]
