# Generated by Django 4.2.1 on 2023-06-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_auto_20230620_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objeto',
            new_name='Trinket',
        ),
    ]
