# Generated by Django 5.0.6 on 2024-06-30 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_alter_trinket_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tiempo_espera_min', models.IntegerField()),
                ('tiempo_espera_max', models.IntegerField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='cerrado', max_length=7)),
                ('imagen', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='cerrado', max_length=7)),
                ('tiempo_espera_min', models.IntegerField()),
                ('tiempo_espera_max', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.DeleteModel(
            name='Trinket',
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Registro.tienda'),
        ),
    ]
