# Generated by Django 5.0.6 on 2024-06-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0008_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
