# Generated by Django 4.2.1 on 2023-06-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_rename_objeto_trinket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trinket',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Opción 1'), (2, 'Opción 2'), (3, 'Opción 3'), (4, 'Opción 4')]),
        ),
    ]
